spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/admin
      database: ${MONGO_DATABASE}

sentry:
  service: ${SERVICE_DSN}

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}